// Auto-generates a HANDBOOK.md at the repo root the first time a user interacts
// with a project (chat or pipeline). It introduces the repository and explains
// how to generate a full structured handbook with Handbook Studio.
//
// Deterministic by design: it must run instantly, offline, and without consuming
// any LLM quota, so it builds the summary from a lightweight filesystem scan.
import fs from 'fs';
import path from 'path';

const SKIP_DIRS = new Set([
  '.git', 'node_modules', '.handbook', '__pycache__', '.venv', 'venv', 'env',
  'dist', 'build', '.idea', '.vscode', '.next', 'target', '.pytest_cache',
  '.mypy_cache', 'coverage', '.turbo', '.cache',
]);

const LANG_BY_EXT = {
  '.py': 'Python', '.ts': 'TypeScript', '.tsx': 'TypeScript (React)',
  '.js': 'JavaScript', '.jsx': 'JavaScript (React)', '.go': 'Go',
  '.rs': 'Rust', '.java': 'Java', '.rb': 'Ruby', '.c': 'C', '.h': 'C/C++ header',
  '.cpp': 'C++', '.cc': 'C++', '.cs': 'C#', '.kt': 'Kotlin', '.swift': 'Swift',
  '.php': 'PHP', '.scala': 'Scala', '.sh': 'Shell',
};

function scanRepo(root, { maxFiles = 8000, maxDepth = 7 } = {}) {
  const extCounts = {};
  const dirCodeCounts = {}; // rel dir -> code file count (for scope suggestion)
  let topDirs = [];
  let fileCount = 0;

  try {
    topDirs = fs
      .readdirSync(root, { withFileTypes: true })
      .filter((d) => d.isDirectory() && !SKIP_DIRS.has(d.name) && !d.name.startsWith('.'))
      .map((d) => d.name)
      .sort();
  } catch {
    return null;
  }

  const stack = [{ dir: root, depth: 0 }];
  while (stack.length && fileCount < maxFiles) {
    const { dir, depth } = stack.pop();
    let entries = [];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const e of entries) {
      if (e.name.startsWith('.')) continue;
      if (e.isDirectory()) {
        if (SKIP_DIRS.has(e.name)) continue;
        if (depth < maxDepth) stack.push({ dir: path.join(dir, e.name), depth: depth + 1 });
      } else if (e.isFile()) {
        fileCount++;
        const ext = path.extname(e.name).toLowerCase();
        if (ext) extCounts[ext] = (extCounts[ext] || 0) + 1;
        if (LANG_BY_EXT[ext]) {
          const rel = path.relative(root, dir) || '.';
          dirCodeCounts[rel] = (dirCodeCounts[rel] || 0) + 1;
        }
      }
    }
  }
  return { extCounts, dirCodeCounts, topDirs, fileCount };
}

function topLanguages(extCounts, n = 4) {
  const byLang = {};
  for (const [ext, count] of Object.entries(extCounts)) {
    const lang = LANG_BY_EXT[ext];
    if (lang) byLang[lang] = (byLang[lang] || 0) + count;
  }
  return Object.entries(byLang)
    .sort((a, b) => b[1] - a[1])
    .slice(0, n)
    .map(([lang, count]) => `${lang} (${count} files)`);
}

// Suggest the densest, reasonably-deep source directory as a generation scope.
function suggestScope(dirCodeCounts) {
  const candidates = Object.entries(dirCodeCounts)
    .filter(([rel]) => rel !== '.' && !rel.includes('test'))
    .sort((a, b) => b[1] - a[1]);
  if (!candidates.length) return null;
  // Prefer a directory that has a meaningful path depth (a real package).
  const deep = candidates.find(([rel]) => rel.split(path.sep).length >= 2);
  return (deep || candidates[0])[0];
}

function renderIntro(project, scan) {
  const name = project.name || path.basename(project.path);
  const langs = scan ? topLanguages(scan.extCounts) : [];
  const scope = scan ? suggestScope(scan.dirCodeCounts) : null;
  const topDirs = scan?.topDirs || [];
  const scopeLine = scope
    ? `\`${scope}\``
    : 'a focused subfolder (e.g. a single agent/package) — leave blank to scan the whole repo';

  return `# HANDBOOK.md

> Auto-generated by **Handbook Studio** when you opened **${name}** and started
> working with it. It introduces this repository and explains how to produce a
> full, structured **code handbook** for it. Safe to edit or delete — it is only
> regenerated if removed.

## About this repository

- **Name:** ${name}
- **Location:** \`${project.path}\`
${langs.length ? `- **Primary languages:** ${langs.join(', ')}` : ''}
${scan ? `- **Files scanned:** ${scan.fileCount}${scan.fileCount >= 8000 ? '+ (truncated)' : ''}` : ''}
${topDirs.length ? `- **Top-level layout:** ${topDirs.map((d) => `\`${d}/\``).join(', ')}` : ''}
${scope ? `- **Suggested generation scope:** \`${scope}\` (densest source tree found)` : ''}

This repo is a *harness* — a codebase whose behavior is best understood as a
lifecycle of stages and the state that flows between them. A handbook makes that
lifecycle explicit so a human (or an AI agent) can navigate it quickly.

## What a "handbook" is

Handbook Studio analyzes the code and produces, under \`.handbook/\` in this repo:

- **Call graph** — who calls whom (built from the AST, no LLM).
- **Skeleton** — the lifecycle *stages* and the *state registers* that carry data
  between them.
- **Stage + function docs** — plain-language explanations of each stage and the
  functions mapped into it, with \`file:line\` references.
- **\`SKILL.md\`** — a compact, agent-loadable summary so a coding agent can use
  the handbook as context.

## How to start a handbook

1. In **Handbook Studio**, select **${name}** in the left sidebar.
2. (Recommended) Set the **scope** field to ${scopeLine}. A tight scope keeps
   generation fast and cheap.
3. Pick a **Quality** mode:
   - **Thorough** — full actor-critic (best quality, most LLM calls).
   - **Fast** — one critic, no revise rounds (good default).
   - **Minimal** — actor only, no critic (fastest, roughest).
4. Click **Generate full handbook**. Live progress streams in the Workspace.
5. When it finishes, open the **Handbook** or **Split view** tab to explore the
   call graph, stages, and state registers — and chat with the agent grounded in
   the generated handbook.

## Pipeline phases

| # | Phase | What it does | LLM cost |
|---|-------|--------------|----------|
| 1 | Map call graph | AST extraction of functions + call edges | none |
| 2 | Draft skeleton | propose lifecycle stages + registers | ~1 call |
| 3 | Classify stages | map each function into a stage (actor-critic) | bulk |
| 4 | Write docs | per-stage + per-function explanations | bulk |

## Chatting with the agent

Ask questions about this repo in the Workspace. Once the handbook exists, its
overview, stage/register index, and registers are attached to every message, and
in **Split view** you can click a stage or function to focus the chat on it
("explain this").

---
*Generated ${new Date().toISOString()} · Handbook Studio*
`;
}

/**
 * Ensure a HANDBOOK.md exists at the repo root.
 * @returns {{ path: string, created: boolean }}
 */
export function ensureHandbookIntro(project, { force = false } = {}) {
  const target = path.join(project.path, 'HANDBOOK.md');
  if (!force && fs.existsSync(target)) {
    return { path: target, created: false };
  }
  let scan = null;
  try {
    scan = scanRepo(project.path);
  } catch {
    scan = null;
  }
  fs.writeFileSync(target, renderIntro(project, scan), 'utf8');
  return { path: target, created: true };
}
